### ISSUE TITLE
Reevaluate gradle_build promotion

### ISSUE THREAD

**Issue by sofusalbertsen** [eficode-academy/artifactory-katas#47]
Reevaluate gradle_build, whether the promoteBuild is presented wrong. It is a home-made curl, not something smart and built into gradle. Maybe we should say that, maybe it shouldn't be there at all.

Perhaps do a disclaimer in the comments of build.gradle, saying that promoteBuild is an example task, and that production systems should use html libraries to do REST calls.

**Comment by MichaelMadsen** [comment]
A disclaimer has been added, both in the exercise README and in the code.
In the case where the curl has to be manually run, the task now politely tells the user to run the curl.

Still not the greatest of situations. Not sure I want to close the issue, as the discussion of whether it should be there at all is still valid.
Maybe we want to change it so it *always* just prints out a curl for the user to run. Then we don't do anything hacky, we just acknowledge that we are not doing this through gradle.
