### ISSUE TITLE
acme or duckcorp?

### ISSUE THREAD

**Issue by RandomSort** [eficode-academy/artifactory-katas#53]
Is there a reason that we are using acme and duckcorp / foxcorp? Consistency is lovely.

I noticed this in the gradle_intro exercises.

**Comment by figaw** [comment]
Tbh I think it's like your "horse" and afai-guess duck-/foxcorp is from @MichaelMadsen and acme is from @sofusalbertsen.

Though I think they're supposed to reflect that: 
- com.acme is used when the group doesn't matter
- com.duckcorp and com.foxcorp is used to distinguish different "companies"

But in the `gradle_intro`-exercise there's just a reference to duckcorp. Thoughts @sofusalbertsen @MichaelMadsen ?
