### ISSUE TITLE
rename and document setup/artifactory-pro.yml

### ISSUE THREAD

**Issue by figaw** [eficode-academy/artifactory-katas#62]
There's a docker compose file inside the `setup` folder.

It isn't documented (possibly dupe of #4) 

It has a non-standard name for a docker-compose file, which would just be `docker-compose.yaml` so people have to explicitly add the `filename` flag or rename the file. While I think it's useful for several different docker-compose files in the same folder to have a descriptive name, it's not helpful in this context of the Artifactory exercises when there's only one.

**Comment by sofusalbertsen** [comment]
Agree, will improve.
