### ISSUE TITLE
Create Repository: There is no longer a "native browser" menu item

### ISSUE THREAD

**Issue by michaelin** [eficode-academy/artifactory-katas#71]
There is no longer a "native browser" menu when right-clicking on a in Artifactory. Describe how to get the URL from the artifact and simply open it in a browser of your choise (chrome, curl...)

https://github.com/praqma-training/artifactory-katas/tree/master/create_repository#look-at-them-through-the-native-browser

**Comment by mtavi** [comment]
There is now again the native browser menu with the latest JFrog Cloud artifactory ( I suppose 7.something ) as well as 6.23.7.

Getting the URL is added to gradle_intro where the url is picked from the repository, see PR #83
